#    _____           _        _    _____               _ 
#   |  __ \         | |      | |  / ____|             | |
#   | |__) |__   ___| | _____| |_| |     _ __ ___   __| |
#   |  ___/ _ \ / __| |/ / _ \ __| |    | '_ ` _ \ / _` |
#   | |  | (_) | (__|   <  __/ |_| |____| | | | | | (_| |
#   |_|   \___/ \___|_|\_\___|\__|\_____|_| |_| |_|\__,_|
#                                                        
#                                                        

cmd-messages:
 example: "This is a example command. Edit it with /pcmd edit example <new message>
